export const DB_PATH = new URL('../data/ecdo.db', import.meta.url).pathname;

export const NOMINAL_OMEGA_PICORAD_S = 72921151.467064;
export const ARCSEC_TO_RAD = Math.PI / (180 * 3600);
export const AU_KM = 149597870.7;

export const WEATHER_GRID = [
  { id: 'nyc', label: 'New York', lat: 40.7, lon: -74.0 },
  { id: 'miami', label: 'Miami', lat: 25.8, lon: -80.2 },
  { id: 'la', label: 'Los Angeles', lat: 34.1, lon: -118.2 },
  { id: 'anchorage', label: 'Anchorage', lat: 61.2, lon: -149.9 },
  { id: 'london', label: 'London', lat: 51.5, lon: -0.1 },
  { id: 'paris', label: 'Paris', lat: 48.9, lon: 2.3 },
  { id: 'moscow', label: 'Moscow', lat: 55.8, lon: 37.6 },
  { id: 'cairo', label: 'Cairo', lat: 30.0, lon: 31.2 },
  { id: 'nairobi', label: 'Nairobi', lat: -1.3, lon: 36.8 },
  { id: 'mumbai', label: 'Mumbai', lat: 19.1, lon: 72.9 },
  { id: 'beijing', label: 'Beijing', lat: 39.9, lon: 116.4 },
  { id: 'tokyo', label: 'Tokyo', lat: 35.7, lon: 139.7 },
  { id: 'sydney', label: 'Sydney', lat: -33.9, lon: 151.2 },
  { id: 'saopaulo', label: 'São Paulo', lat: -23.5, lon: -46.6 },
  { id: 'equator_pacific', label: 'Equator Pacific', lat: 0, lon: -160 },
  { id: 'equator_africa', label: 'Equator Africa', lat: 0, lon: 20 },
];

export const STORM_EVENT_TYPES = new Set([
  'Tornado',
  'Hurricane',
  'Typhoon',
  'Tropical Storm',
  'Tropical Depression',
  'Flash Flood',
  'Flood',
  'Hail',
  'Winter Storm',
  'Blizzard',
  'Ice Storm',
  'Heavy Rain',
  'High Wind',
  'Thunderstorm Wind',
  'Dust Storm',
  'Wildfire',
  'Extreme Cold/Wind Chill',
  'Excessive Heat',
]);

export const EPHEMERIS_BODIES = [
  { id: '301', key: 'moon', name: 'Moon' },
  { id: '10', key: 'sun', name: 'Sun' },
  { id: '199', key: 'mercury', name: 'Mercury' },
  { id: '299', key: 'venus', name: 'Venus' },
  { id: '499', key: 'mars', name: 'Mars' },
  { id: '599', key: 'jupiter', name: 'Jupiter' },
  { id: '699', key: 'saturn', name: 'Saturn' },
];

export const SOURCES = {
  iersEop: {
    name: 'IERS Earth Orientation Parameters C04',
    org: 'IERS',
    citation: 'Bizouard et al., IERS EOP C04 ITRF 2020',
    link: 'https://hpiers.obspm.fr/eop-pc/index.php?index=C04&lang=en',
    epistemic: 'measured',
    ingestKeys: ['eop'],
  },
  usgsEarthquakes: {
    name: 'USGS Earthquake Catalog',
    org: 'U.S. Geological Survey',
    citation: 'USGS FDSN Event Web Service',
    link: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    epistemic: 'measured',
    ingestKeys: ['earthquakes', 'earthquakes-incremental'],
  },
  gvpEruptions: {
    name: 'Smithsonian GVP Eruptions Since 1960',
    org: 'Smithsonian GVP',
    citation: 'GVP E3WebApp_Eruptions1960',
    link: 'https://volcano.si.edu/database/webservices.cfm',
    epistemic: 'measured',
    ingestKeys: ['eruptions'],
  },
  gvpVolcanoes: {
    name: 'Smithsonian GVP Holocene Volcanoes',
    org: 'Smithsonian GVP',
    citation: 'GVP Holocene Volcano List',
    link: 'https://volcano.si.edu/gvp_votw.cfm',
    epistemic: 'measured',
    ingestKeys: ['volcanoes'],
  },
  jplHorizons: {
    name: 'JPL Horizons Ephemeris',
    org: 'NASA JPL',
    citation: 'Horizons API, DE441',
    link: 'https://ssd.jpl.nasa.gov/horizons/',
    epistemic: 'measured',
    ingestKeys: ['ephemeris'],
  },
  openMeteo: {
    name: 'Open-Meteo Historical Weather',
    org: 'Open-Meteo',
    citation: 'ERA5 reanalysis archive API',
    link: 'https://open-meteo.com/en/docs/historical-weather-api',
    epistemic: 'modeled',
    ingestKeys: ['weather'],
  },
  noaaStorms: {
    name: 'NOAA Storm Events Database',
    org: 'NOAA NCEI',
    citation: 'NCEI Storm Events CSV',
    link: 'https://www.ncei.noaa.gov/stormevents/',
    epistemic: 'measured',
    ingestKeys: ['storms'],
  },
  nasaSunspot: {
    name: 'International Sunspot Number',
    org: 'NASA MSFC / SILSO',
    citation: 'Monthly sunspot (expanded to daily)',
    link: 'https://solarscience.msfc.nasa.gov/greenwch/',
    epistemic: 'measured',
    ingestKeys: ['solar'],
  },
  nasaDonki: {
    name: 'NASA DONKI Space Weather',
    org: 'NASA CCMC',
    citation: 'CME, flare, and geomagnetic storm catalog',
    link: 'https://api.nasa.gov/DONKI/docs',
    epistemic: 'measured',
    ingestKeys: ['space-weather', 'donki'],
  },
  plateBoundaries: {
    name: 'PB2002 Plate Boundaries',
    org: 'Bird (2003) / NOAA NGDC',
    citation: 'Global tectonic plate boundary model PB2002',
    link: 'https://www.ngdc.noaa.gov/mgg/ocean/plate_boundary/',
    epistemic: 'pedagogical',
    ingestKeys: [],
  },
  intermagnet: {
    name: 'INTERMAGNET Observatory Network',
    org: 'INTERMAGNET / BGS World Data Centre',
    citation: 'Global magnetometer observatory metadata (EPOS GeoJSON)',
    link: 'https://www.intermagnet.org/',
    epistemic: 'measured',
    ingestKeys: ['geomag'],
  },
  igrf14: {
    name: 'IGRF-14 Geomagnetic Reference Field',
    org: 'IAGA / NOAA NCEI / BGS',
    citation: 'International Geomagnetic Reference Field, 14th generation',
    link: 'https://www.ncei.noaa.gov/products/international-geomagnetic-reference-field',
    epistemic: 'modeled',
    ingestKeys: [],
  },
  igrfWmm: {
    name: 'World Magnetic Model (legacy field lines)',
    org: 'NOAA NCEI',
    citation: 'WMM2020 dipole L-shell traces (retired visualization)',
    link: 'https://www.ncei.noaa.gov/products/world-magnetic-model',
    epistemic: 'pedagogical',
    ingestKeys: [],
  },
  mantleHotspots: {
    name: 'Wilson Mantle Hotspots',
    org: 'Smithsonian GVP / plate tectonic synthesis',
    citation: 'Reference hotspot surface positions',
    link: 'https://volcano.si.edu/glossary/Hotspot/',
    epistemic: 'pedagogical',
    ingestKeys: [],
  },
  plateMotion: {
    name: 'PB2002 Plate Motion (Euler poles)',
    org: 'Peter Bird / DeMets et al.',
    citation: 'PB2002 angular velocities in deg/Ma',
    link: 'http://peterbird.name/oldFTP/PB2002/PB2002_poles.dat.txt',
    epistemic: 'derived',
    ingestKeys: [],
  },
  noaaSwpc: {
    name: 'NOAA Space Weather Prediction Center',
    org: 'NOAA SWPC',
    citation: 'Planetary K-index and daily geomagnetic indices',
    link: 'https://www.swpc.noaa.gov/products/planetary-k-index',
    epistemic: 'derived',
    ingestKeys: ['space-weather', 'kp'],
  },
  kyotoDst: {
    name: 'Dst Geomagnetic Index',
    org: 'WDC for Geomagnetism, Kyoto',
    citation: 'Hourly equatorial Dst (storm-time ring current)',
    link: 'https://wdc.kugi.kyoto-u.ac.jp/dstae/index.html',
    epistemic: 'measured',
    ingestKeys: ['omni'],
  },
  omniSolarWind: {
    name: 'OMNI Near-Earth Solar Wind',
    org: 'NASA GSFC SPDF',
    citation: 'OMNI2 hourly IMF and plasma parameters',
    link: 'https://omniweb.gsfc.nasa.gov/',
    epistemic: 'measured',
    ingestKeys: ['omni'],
  },
  noaaDscovr: {
    name: 'DSCOVR Real-Time Solar Wind',
    org: 'NOAA SWPC',
    citation: 'ACE/DSCOVR L1 magnetic field and plasma (1-day)',
    link: 'https://www.swpc.noaa.gov/products/real-time-solar-wind',
    epistemic: 'measured',
    ingestKeys: [],
  },
  ovationAurora: {
    name: 'OVATION Aurora Forecast',
    org: 'NOAA SWPC',
    citation: 'Auroral oval probability model (nowcast)',
    link: 'https://www.swpc.noaa.gov/products/aurora-30-minute-forecast',
    epistemic: 'derived',
    ingestKeys: [],
  },
  gfzAam: {
    name: 'Atmospheric Angular Momentum (AAM)',
    org: 'GFZ Potsdam',
    citation: 'ESMGFZ operational AAM v1.0 (ECMWF analysis, 3h)',
    link: 'https://www.gfz.de/en/sektion/erdsystem-modellierung/esmdata/esmdata/eam/',
    epistemic: 'derived',
    ingestKeys: ['aam'],
  },
  ibtracs: {
    name: 'IBTrACS Global Tropical Cyclones',
    org: 'NOAA NCEI',
    citation: 'International Best Track Archive for Climate Stewardship v04r01',
    link: 'https://www.ncei.noaa.gov/products/international-best-track-archive',
    epistemic: 'measured',
    ingestKeys: ['ibtracs'],
  },
};